added first version of task 7.2 (doesn't work)
daniil-steperev/spbuHomework pull request #108
Opened 2019-04-20 20:14 UTC by daniil-steperev

2019-05-05 14:14 UTC, jzuken requested changes

2019-05-05 14:14 UTC, jzuken commented on sem2/Homework7/task2/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
это не надо выкладывать

2019-05-05 14:14 UTC, jzuken commented on sem2/Homework7/task2/build.gradle
> +    testCompile group: 'junit', name: 'junit', version: '4.12'
ну как бы у тебя пятый junit использутся в тестах

2019-05-05 14:14 UTC, jzuken commented on sem2/Homework7/task2/src/main/java/group144/stepyrev/buildClass/DifficultClass.java
> +public class DifficultClass<T> extends Object implements group144.stepyrev.test.DifficultClassInterface<T> {
если это для тестов код, то его и надо в папку рядом с тестами класть

2019-05-05 14:14 UTC, jzuken commented on sem2/Homework7/task2/src/main/java/group144/stepyrev/ClassBuilder.java
> +            buildClass.append(Modifier.toString(method.getModifiers()) + " ");
посмотри на эту строчку. тебя ничего не смушает в ней?

2019-05-05 14:14 UTC, jzuken commented on sem2/Homework7/task2/src/main/java/group144/stepyrev/ClassBuilder.java
> +        for (int i = 0; i < firstClassFields.length; i++) {
лучше заменить на foreach

2019-05-06 07:34 UTC, daniil-steperev commented
package buildClass -- пакет, в который помещаются все построенные классы;
package testClasses -- пакет, в котором находятся файлы необходимые для тестов **

** пакет testClasses есть также и в main. Это необходимо для того, чтобы был приличный импорт интерфейса для DifficultClass.

2019-05-17 11:40 UTC, jzuken requested changes

2019-05-17 11:40 UTC, jzuken commented on sem2/Homework7/task2/build.gradle
> +sourceCompatibility = 11
а ты попробуй это всё запустить:

✗ ./gradlew test
Downloading https://services.gradle.org/distributions/gradle-4.10-bin.zip
..........................................................................

Welcome to Gradle 4.10!

...

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not target platform: 'Java SE 11' using tool chain: 'JDK 8 (1.8)'.

2019-05-17 11:52 UTC, daniil-steperev commented on sem2/Homework7/task2/build.gradle
> +sourceCompatibility = 11
@jzuken Здравствуйте! У меня проходит билд. Или я что-то делаю не так?
![image](https://user-images.githubusercontent.com/43496856/57926152-367ab000-78b3-11e9-9b9c-05760b0bad47.png)

2019-05-17 13:04 UTC, daniil-steperev commented on sem2/Homework7/task2/build.gradle
> +sourceCompatibility = 11
И в IDEA:
![image](https://user-images.githubusercontent.com/43496856/57929980-6dee5a00-78bd-11e9-9bb5-ff318446025c.png)

2019-05-17 13:26 UTC, merged