9.1.java
daniil-steperev/spbuHomework pull request #111
Opened 2019-05-01 09:40 UTC by daniil-steperev

2019-05-11 11:06 UTC, jzuken commented
закрываю крестиком приложения, а оно всё ещё работает

2019-05-11 11:07 UTC, jzuken commented
если нажать new game, то дальше окна начинают жить каждое своей жизнью

2019-05-11 11:10 UTC, jzuken requested changes

2019-05-11 11:10 UTC, jzuken commented on sem2/Homework9/task1/src/main/java/group144/stepyrev/ClientController.java
> +            if (buttons[i].equals(event.getSource())) {
а можно эти контроллеры написать без столь яростной копипасты?

2019-05-11 11:10 UTC, jzuken commented on sem2/Homework9/task1/src/main/java/group144/stepyrev/TicTacToeBoard.java
> +        return size;
это поле только здесь и используется

2019-05-12 12:27 UTC, daniil-steperev commented
HOW TO START A NEW GAME AFTER ENDING A PREVIOUS ONE:
1. User of the server should press 'New game';
2. User of the client should press 'New game'.

2019-06-06 08:46 UTC, merged