4.1
daniil-steperev/spbuHomework pull request #21
Opened 2018-10-16 19:58 UTC by daniil-steperev

2018-10-24 18:26 UTC, ujohnny commented
можно было просто сделать interactive rebase на master или origin/master и выкинуть 
cfa6b90 из истории, чтобы не создавать 214c208

2018-10-24 18:39 UTC, ujohnny requested changes

2018-10-24 18:39 UTC, ujohnny commented on sem1/hw4/task1/loopedList.cpp
> +#include "loopedList.h"
круто, только он cyclic, а не looped

2018-10-24 18:39 UTC, ujohnny commented on sem1/hw4/task1/loopedList.cpp
> +    ListElement *position;
position? почему так называется?

2018-10-24 18:39 UTC, ujohnny commented on sem1/hw4/task1/main.cpp
> +    for (int i = 1; i <= n; ++i)
почему здесь и везде ниже с 1го начинается, а не с 0?

2018-10-24 18:39 UTC, ujohnny commented on sem1/hw4/task1/loopedList.cpp
> +    while ((current->next != list->first) && (current->next->value < value))
то есть он еще и сортированный. а по его называнию не скажешь

2018-10-24 18:39 UTC, ujohnny commented on sem1/hw4/task1/loopedList.cpp
> +{
как то странно что удаление элемента из обычного списка обладает какой то логикой по вычислениям внутри. вы зря это внутрь положили, ваш список должен быть обычным списком и больше ничем

2018-10-24 18:39 UTC, ujohnny commented on sem1/hw4/task1/main.cpp
> +        printf("Test 1 successfully passed.\n");
спорно видеть такой аутпут во время обычной работы программы

2018-10-27 15:14 UTC, jzuken commented on sem1/hw4/task1/main.cpp
> +        printf("Test 1 successfully passed.\n");
ну это я их просил так делать, пока тесты нормально не умеем писать. лучше пусть так пишут, чем вообще никак

2018-11-02 08:21 UTC, jzuken commented
чтобы замечание про interactive rebase не осталось просто пустыми словами, предлагаю это всё же сделать

2018-11-07 11:37 UTC, jzuken commented
я полагаю, Евгений имел в виду, что стоит сделать новую ветку, и сделать туда rebase так, чтобы в истории не было мусорных ненужных коммитов

2018-12-21 19:04 UTC, closed without merging