added problem 6.2 (task about converting decimal number to the binary and counting sum in binary system)
daniil-steperev/spbuHomework pull request #31
Opened 2018-11-01 15:35 UTC by daniil-steperev

… and counting sum in binary system)

2018-11-02 13:07 UTC, jzuken commented
Enter two numbers: -5 11
First number in binary code: Stack is empty!

2018-11-02 13:10 UTC, jzuken requested changes

2018-11-02 13:10 UTC, jzuken commented on sem1/hw6/task2/binary.cpp
> +    Stack *reversedSecond = createStack();
и кто его удалит?

2018-11-02 13:10 UTC, jzuken commented on sem1/hw6/task2/binary.cpp
> +    Stack *reversedFirst = createStack();
а зачем тут вообще стек?

2018-11-07 11:43 UTC, jzuken requested changes

2018-11-07 11:43 UTC, jzuken commented on sem1/hw6/task2/binary.cpp
> +    int *sumOfBinary = new int[size] {0};
массив размера 0 это сильно

2018-11-07 11:43 UTC, jzuken commented on sem1/hw6/task2/binary.cpp
> +void summing(int firstNumber, int secondNumber)
имя функции -- глагол. `sum`.

2018-11-07 11:43 UTC, jzuken commented on sem1/hw6/task2/binary.cpp
> +void reverseStack(Stack *oldStack, Stack *reversedStack)
и я не вижу ответа на вопрос, зачем тебе тут именно стек. зато я вижу целую кучу кода, которая показывает, что стек крайне неудачный выбор типа данных для хранения

2018-11-17 06:35 UTC, jzuken requested changes

2018-11-17 06:35 UTC, jzuken commented on sem1/hw6/task2/operations.cpp
> +    sum(firstNumber, secondNumber);
operations.cpp:17:34: error: ‘sum’ was not declared in this scope

2018-11-24 16:38 UTC, jzuken requested changes

2018-11-24 16:38 UTC, jzuken commented on sem1/hw6/task2/operations.cpp
> +<<<<<<< HEAD
ты походу издеваешься

2018-11-24 19:31 UTC, daniil-steperev commented on sem1/hw6/task2/operations.cpp
> +<<<<<<< HEAD
Извините, не проверил содержимое файлов.

2018-12-04 11:27 UTC, jzuken requested changes

2018-12-04 11:27 UTC, jzuken commented on sem1/hw6/task2/operations.h
> +#include "stack.h"
In file included from main.cpp:2:0:
operations.h:2:19: fatal error: stack.h: No such file or directory
compilation terminated.
In file included from operations.cpp:3:0:
operations.h:2:19: fatal error: stack.h: No such file or directory

![image](https://user-images.githubusercontent.com/705678/49438921-b9f68800-f7d0-11e8-8e56-580704ff5763.png)

2018-12-17 14:21 UTC, merged