added task 6.1 (converting double number to exponential form)
daniil-steperev/spbuHomework pull request #35
Opened 2018-11-06 18:03 UTC by daniil-steperev

2018-11-08 20:43 UTC, ujohnny requested changes

2018-11-08 20:43 UTC, ujohnny commented on sem1/hw6/task1/convertToExponential.cpp
> +    countSign(bytes);
может быть все таки стоит сделать нормальными ф-ми, которые возвращают какое то значение?

2018-11-08 20:43 UTC, ujohnny commented on sem1/hw6/task1/convertToExponential.cpp
> +    unsigned char *bytes = (unsigned char*)&number;
c-style cast в с++ нельзя

2018-11-08 20:43 UTC, ujohnny commented on sem1/hw6/task1/convertToExponential.cpp
> +    if (number == 0.0)
это не всегда будет работать.

2018-11-08 20:43 UTC, ujohnny commented on sem1/hw6/task1/convertToExponential.h
> +void convertToExponential(double number);
а что же оно convert и при этом void?

2018-11-08 20:43 UTC, ujohnny commented on sem1/hw6/task1/convertToExponential.cpp
> +    if (sign == 1)
тут тоже довольно странный код с return совсем не к месту

2018-11-08 20:43 UTC, ujohnny commented on sem1/hw6/task1/convertToExponential.cpp
> +    int order = (bytes[7] & orderMask) * 16 + (bytes[6] & orderBeforeMantissa) / 16 - orderShift;
почемиу 16? что это за константа?

2018-11-11 12:04 UTC, jzuken requested changes

2018-11-11 12:04 UTC, jzuken commented on sem1/hw6/task1/convertToExponential.cpp
> +        mantissaOrder *= 256;
лучше явно использовать битовый сдвиг

2018-11-11 12:04 UTC, jzuken commented on sem1/hw6/task1/convertToExponential.cpp
> +void countSign(unsigned char *bytes)
если функция что-то печатает, то надо так явно и писать. а то сейчас функции действительно называются противоестественно

2018-11-11 12:04 UTC, jzuken commented on sem1/hw6/task1/convertToExponential.cpp
> +    if (number == 0.0)
имеется в виду, что даблы это всегда приближённые значения. стоит проверять, что разница попадает в некоторую небольшую дельта-окрестность

2018-11-20 10:47 UTC, merged