added task 8.2 (structure string)
daniil-steperev/spbuHomework pull request #38
Opened 2018-11-15 17:32 UTC by daniil-steperev

2018-11-20 10:53 UTC, jzuken requested changes

2018-11-20 10:53 UTC, jzuken commented on sem1/hw8/task2/test.cpp
> +void test()
очень много памяти утекает

2018-11-20 10:53 UTC, jzuken commented on sem1/hw8/task2/myString.h
> +bool is_Empty(MyString *str);
стайлгайд отменили?

2018-12-03 08:06 UTC, jzuken requested changes

2018-12-03 08:06 UTC, jzuken commented on sem1/hw8/task2/myString.cpp
> +bool are_Equal(MyString *stringFirst, MyString *stringSecond)
замечание про стайлгайд было не про имена параметров, а про имена функций тут

2018-12-03 08:06 UTC, jzuken commented on sem1/hw8/task2/myString.cpp
> +    return newContent;
HEAP SUMMARY:
  in use at exit: 73,131 bytes in 21 blocks
total heap usage: 31 allocs, 10 frees, 77,468 bytes allocated

например, кто вот эти возвращаемые строки удаляет?

2018-12-03 16:49 UTC, daniil-steperev commented on sem1/hw8/task2/myString.cpp
> +    return newContent;
Спасибо!

2018-12-16 13:41 UTC, jzuken requested changes

2018-12-16 13:41 UTC, jzuken commented on sem1/hw8/task2/test.cpp
> +    string = concatenate(string, concString);
ещё есть проблемы с памятью

2018-12-21 08:40 UTC, merged