added task 5.5
daniil-steperev/spbuHomework pull request #48
Opened 2018-11-18 17:55 UTC by daniil-steperev

2018-11-24 17:22 UTC, jzuken requested changes

2018-11-24 17:22 UTC, jzuken commented on sem1/hw5/task5/convertToPostfix.cpp
> +#include "stack.h"
а нету такого файла. давай ты будешь после выкладывания задач клонировать их в отдельный репозиторий и проверять, что всё собирается хотя бы?

2018-11-24 19:24 UTC, daniil-steperev commented on sem1/hw5/task5/convertToPostfix.cpp
> +#include "stack.h"
Извините, что невнимательно отправляю задачи ;(.

2018-11-24 19:41 UTC, jzuken commented on sem1/hw5/task5/convertToPostfix.cpp
> +#include "stack.h"
извинения не интересны, нужен результат

2018-12-04 11:24 UTC, jzuken requested changes

2018-12-04 11:24 UTC, jzuken commented on sem1/hw5/task5/convertToPostfix.cpp
> +void convertingToPostfix(char *infixString)
а теперь давай переименуем все функции, чтобы они были глаголами. функция -- действие, а не процесс, как тут сейчас

2018-12-17 14:20 UTC, merged