added task 8.3 with testing file
daniil-steperev/spbuHomework pull request #50
Opened 2018-11-18 18:02 UTC by daniil-steperev

2018-11-23 07:59 UTC, daniil-steperev commented
Извините, еще не успел исправить ошибку в myString.h и myString.cpp (стайлгайд).

2018-11-24 17:33 UTC, jzuken requested changes

2018-11-24 17:33 UTC, jzuken commented on sem1/hw8/task3/main.cpp
> +int main()
ну тут с памятью всё очень плохо

2018-11-24 21:20 UTC, daniil-steperev commented on sem1/hw8/task3/main.cpp
> +int main()
Переписал удаление hashTable. В Visual Studio 2017 на vld тесте выдает 176 memory leak. Если Вам нетрудно, подскажите, пожалуйста, в чем проблема.

2018-12-04 12:05 UTC, jzuken requested changes

2018-12-04 12:05 UTC, jzuken commented on sem1/hw8/task3/list.cpp
> +void add(List *list, MyString *str)
посмотри, что происходит со строками при добавлении их сюда

2018-12-04 12:05 UTC, jzuken commented on sem1/hw8/task3/list.cpp
> +        cout << returnChar(current->content) << " ";
и вот сюда надо посмотреть

2018-12-17 16:58 UTC, merged