added task 1 from hw 1 (stack)
daniil-steperev/spbuHomework pull request #79
Opened 2019-02-23 08:43 UTC by daniil-steperev

2019-03-03 20:45 UTC, PrikhodkoStanislav requested changes

2019-03-03 20:45 UTC, PrikhodkoStanislav commented on sem2/Homework1/task1/src/group144/stepyrev_daniil/Stack.java
> +        return (length == 0);
В данном случае не обязательно выделять выражение скобками.

2019-03-04 18:26 UTC, PrikhodkoStanislav requested changes

2019-03-04 18:26 UTC, PrikhodkoStanislav commented on sem2/Homework1/task1/src/group144/stepyrev_daniil/Stack.java
> +        Node newElement = new Node(value, head);
Лишняя переменная. Можно сразу в head присвоить новую ноду.

2019-03-11 09:41 UTC, jzuken requested changes

2019-03-11 09:41 UTC, jzuken commented on sem2/Homework1/task1/src/group144/stepyrev_daniil/Stack.java
> +    /** A method that deletes top element from the stack */
ну и было бы неплохо указать, что он делает, когда pop() происходит на пустом стеке

2019-03-11 09:41 UTC, jzuken commented on sem2/Homework1/task1/src/group144/stepyrev_daniil/Stack.java
> +            this.next = null;
это не надо делать ни тут, ни выше при объявлении. такие инициализации за вас виртуальная машина тут делает

2019-04-10 12:55 UTC, merged