added task 1.2 (linked list)
daniil-steperev/spbuHomework pull request #86
Opened 2019-02-28 16:16 UTC by daniil-steperev

2019-03-03 20:09 UTC, PrikhodkoStanislav requested changes

2019-03-03 20:09 UTC, PrikhodkoStanislav commented on sem2/Homework1/task2/src/group144/steperev_daniil/List.java
> +    public List() {
вложенные классы лучше помещать в конец объемлющих

2019-03-03 20:09 UTC, PrikhodkoStanislav commented on sem2/Homework1/task2/src/group144/steperev_daniil/List.java
> +        return (head == null);
Не обязательно заключать выражение в скобки в таком случае.

2019-03-03 20:09 UTC, PrikhodkoStanislav commented on sem2/Homework1/task2/src/group144/steperev_daniil/List.java
> +        current = null;
Так не сработает. Нужно обнулить ссылку на следующий для предпоследнего элемента. Так ты только локальной переменной current присвоишь значение null.

2019-03-03 20:09 UTC, PrikhodkoStanislav commented on sem2/Homework1/task2/src/group144/steperev_daniil/Main.java
> +package group144.steperev_daniil;
Молодец, что проверил работу методов!

2019-03-04 18:34 UTC, PrikhodkoStanislav requested changes

2019-03-04 18:34 UTC, PrikhodkoStanislav commented on sem2/Homework1/task2/src/group144/steperev_daniil/List.java
> +        while (current.next.next != null) {
Проверь случай с одним элементом в списке.

2019-03-04 18:34 UTC, PrikhodkoStanislav commented on sem2/Homework1/task2/src/group144/steperev_daniil/List.java
> +        if (isEmpty() || length - 1 < index) {
Что будет в случае, когда index < 0?

2019-03-08 17:39 UTC, PrikhodkoStanislav requested changes

2019-03-08 17:39 UTC, PrikhodkoStanislav commented on sem2/Homework1/task2/src/group144/steperev_daniil/List.java
> +        else {
Не обязательно делать перевод строки перед else, Можно писать так: } else {

2019-03-08 20:30 UTC, PrikhodkoStanislav requested changes

2019-03-08 20:30 UTC, PrikhodkoStanislav commented on sem2/Homework1/task2/src/group144/steperev_daniil/List.java
> +    public void remove() {
По названию метода непонятно, удаление какого элемента происходит. Если нет параметров, то логично предположить, что происходит удаление всего списка, а это не так.

2019-03-11 09:43 UTC, jzuken requested changes

2019-03-11 09:43 UTC, jzuken commented on sem2/Homework1/task2/src/group144/steperev_daniil/List.java
> +    private boolean isEmpty() {
а чего он закрытый? снаружи никому такая информация не понадобится?

2019-04-10 12:54 UTC, merged