added task 2.1
daniil-steperev/spbuHomework pull request #87
Opened 2019-02-28 16:18 UTC by daniil-steperev

2019-03-08 20:25 UTC, PrikhodkoStanislav requested changes

2019-03-08 20:25 UTC, PrikhodkoStanislav commented on sem2/Homework2/task1/src/main/java/group144/sorter/stepyrev/SelectionSort.java
> +/**
однострочные комментарии лучше так и писать в одну строку: /** ... */

2019-03-08 20:25 UTC, PrikhodkoStanislav commented on sem2/Homework2/task1/src/main/java/group144/sorter/stepyrev/ShakerSort.java
> +/**
однострочные комментарии лучше так и писать в одну строку: /** ... */

2019-03-08 20:25 UTC, PrikhodkoStanislav commented on sem2/Homework2/task1/src/main/java/group144/sorter/stepyrev/Sorter.java
> +/**
однострочные комментарии лучше так и писать в одну строку: /** ... */

2019-03-11 09:45 UTC, jzuken commented on sem2/Homework2/task1/src/main/java/group144/sorter/stepyrev/ShakerSort.java
> +package group144.sorter.stepyrev;
было бы логично наоборот, наверное: `group144.stepyrev.sorter`

2019-03-11 09:45 UTC, merged