added task 3.4
daniil-steperev/spbuHomework pull request #9
Opened 2018-10-03 12:57 UTC by daniil-steperev

2018-10-06 09:41 UTC, jzuken requested changes

2018-10-06 09:41 UTC, jzuken commented on sem1/hw3/task4.cpp
> +    printf("Enter the secret number: ");
ну это как-то не особо игра, программа должна сама загадывать число случайным образом

2018-10-10 12:54 UTC, jzuken commented
что-то я не очень понимаю, что программа делает. она должна загадать число, а потом пользователь его должен отгадывать. а у меня получается так:

Do you want to play with computer? (Yes/no) yes
Enter the secret number: 1234
Make a guess again!: 1234
0 COWS, 0 BULLS
Make a guess again!: 5678
0 COWS, 0 BULLS

2018-10-17 16:00 UTC, jzuken commented
Make a guess again!: 0943
4 COWS, 0 BULLS

и продолжает играть

2018-10-18 11:59 UTC, daniil-steperev commented
> Make a guess again!: 0943
> 4 COWS, 0 BULLS
> 
> и продолжает играть

Возможно, я неправильно понял, но ведь в этом случае программа должна работать (так как были угаданы все цифры, но на неверных позициях (на Википедии написано, что "корова" - цифра, угаданная на неверной позиции,а бык - цифра, угаданная на верной позиции)). Если я неправ, поправьте меня, пожалуйста.

2018-10-27 22:35 UTC, merged