added task 1 from hw 3 (hash table)
daniil-steperev/spbuHomework pull request #92
Opened 2019-03-17 10:11 UTC by daniil-steperev

2019-04-15 11:56 UTC, ujohnny requested changes

2019-04-15 11:56 UTC, ujohnny commented on sem2/Homework3/task1/src/main/java/group144/hashtable/stepyrev/HashTable.java
> +     * @throws SimilarHashFunctionException an exception that should be raised when user tries to change hash function to similar one
а почему это считается исключением? ну захотели поменять на такую же, ну ничего менять не надо, в чем проблема?

2019-04-15 11:56 UTC, ujohnny commented on sem2/Homework3/task1/src/main/java/group144/hashtable/stepyrev/Main.java
> +                        reader.close();
он бы все равно закрылся несколько строчек ниже

2019-04-15 11:56 UTC, ujohnny commented on sem2/Homework3/task1/src/main/java/group144/hashtable/stepyrev/HashTable.java
> +        if (hashFunction instanceof SummaryHashFunction && newHashFunction instanceof SummaryHashFunction) {
может быть стоит этот код перенести хотя бы в equals для каждого типа?

2019-04-15 14:44 UTC, ujohnny commented on sem2/Homework3/task1/src/test/java/group144/hashtable/stepyrev/HashTableTest.java
> +        String rightStatistics = "The amount of elements: 8; load factor: 0.03125; number of conflicts: 0; max length of conflict row: 0; empty rows: 248.";
вообще сравнивать строчки -- это совсем не очень. завели бы простой объект и возвращали его и сравнивали их.

2019-04-15 14:44 UTC, ujohnny approved these changes

2019-04-15 14:45 UTC, ujohnny commented
только тут оно конфликтует

2019-04-16 14:54 UTC, daniil-steperev commented
> только тут оно конфликтует

Спасибо за подсказки! Перезалил на https://github.com/daniil-steperev/spbuHomework/pull/106, чтобы проходила проверка Travis.

2019-05-17 20:37 UTC, closed without merging