added task 2 from hw 3 (expression tree)
daniil-steperev/spbuHomework pull request #93
Opened 2019-03-17 10:18 UTC by daniil-steperev

2019-03-22 14:55 UTC, ujohnny commented on sem2/Homework3/task2/src/main/java/group144/expressiontree/stepyrev/Main.java
> +            ExpressionTree expressionTree = new ExpressionTree(expression, 0);
А что же тут за магический ноль вторым аргументом?

2019-03-22 14:56 UTC, ujohnny commented on sem2/Homework3/task2/src/main/java/group144/expressiontree/stepyrev/Main.java
> +            System.out.print("Builded expression tree: ");
Builded -> built

2019-03-22 14:58 UTC, ujohnny commented on sem2/Homework3/task2/src/main/java/group144/expressiontree/stepyrev/Main.java
> +            throw new FileNotFoundException();
Вам не надо создавать новое исключение, достаточно кинуть текущее `throw e`, но в вашем случае из main вылетать ничего не должно

2019-03-22 14:59 UTC, ujohnny commented on sem2/Homework3/task2/src/main/java/group144/expressiontree/stepyrev/Node.java
> +abstract class Node {
А почему не interface?

2019-03-22 15:01 UTC, ujohnny commented on sem2/Homework3/task2/src/main/java/group144/expressiontree/stepyrev/OperatorNode.java
> +            return leftChild.calculate() + rightChild.calculate();
А если окажется что лефт или райт null?

2019-04-14 17:01 UTC, ujohnny approved these changes

2019-04-29 08:41 UTC, jzuken requested changes

2019-04-29 08:41 UTC, jzuken commented on sem2/Homework3/task2/src/main/java/group144/expressiontree/stepyrev/ExpressionTree.java
> +        private Object object;
не надо тут использовать Object. нужен обобщённый тип -- делай себе дженерик

2019-04-29 08:41 UTC, jzuken commented on sem2/Homework3/task2/src/main/java/group144/expressiontree/stepyrev/Node.java
> +abstract class Node {
лучше сделать интерфейсом, да

2019-05-11 10:51 UTC, jzuken requested changes

2019-05-11 10:51 UTC, jzuken commented on sem2/Homework3/task2/src/main/java/group144/expressiontree/stepyrev/ExpressionTree.java
> +        head = (Node) scanTree(expression, 0).object;
хочется разделить построение дерева и парсинг выражения в строке. ну то есть сейчас дерево можно создать только по строке и больше никак

2019-06-06 08:29 UTC, jzuken requested changes

2019-06-06 08:29 UTC, jzuken commented on sem2/Homework3/task2/src/main/java/group144/stepyrev/ExpressionTree.java
> +    private Node head = null;
ну всё, что ты сделал сейчас, это по сути переименовал конструктор. а как создать ненулевое дерево то сейчас?

2019-06-10 15:29 UTC, merged