added task 1 from hw 4 (unique list)
daniil-steperev/spbuHomework pull request #94
Opened 2019-03-17 13:33 UTC by daniil-steperev

2019-04-15 12:03 UTC, ujohnny requested changes

2019-04-15 12:03 UTC, ujohnny commented on sem2/Homework4/task1/src/main/java/group144/uniquelist/stepyrev/List.java
> +        if (index < 0 || index > length - 1) {
это разумнее проверить сразу

2019-04-15 12:03 UTC, ujohnny commented on sem2/Homework4/task1/src/main/java/group144/uniquelist/stepyrev/List.java
> +    public void addLast(T value) throws AlreadyAddedElementException {
у вас тут запутанно с этими last/first получается. мой совет -- реализовывать это все через одну ф-ю, к примеру

```
addLast(T) -> add(T, length)
addFirst(T) -> add(T, 0)
```

2019-04-15 12:03 UTC, ujohnny commented on sem2/Homework4/task1/src/main/java/group144/uniquelist/stepyrev/List.java
> +    public boolean isContain(T value) {
`contains`

2019-04-15 12:03 UTC, ujohnny commented on sem2/Homework4/task1/src/main/java/group144/uniquelist/stepyrev/List.java
> +     * @throws AbsenceElementException an exception that should be raised when user tries to remove missing element
не переусердствуйте с исключениями, сравните к примеру с реализация в jdk

2019-04-15 12:03 UTC, ujohnny commented on sem2/Homework4/task1/src/main/java/group144/uniquelist/stepyrev/UniqueList.java
> +public class UniqueList<T> extends List<T> {
здесь могла быть всего 1 ф-я, а так выходит размазано по тарелке. см коммент выше про first/last

2019-04-29 08:42 UTC, jzuken commented on sem2/Homework4/task1/src/main/java/group144/uniquelist/stepyrev/AbsenceElementException.java
> +public class AbsenceElementException extends Exception {
ElementNotFoundException

2019-05-11 10:50 UTC, jzuken requested changes

2019-05-11 10:50 UTC, jzuken commented on sem2/Homework4/task1/src/main/java/group144/uniquelist/stepyrev/AbsenceElementException.java
> +public class AbsenceElementException extends Exception {
ну он всё ещё тут зачем-то

2019-05-17 13:33 UTC, jzuken requested changes

2019-05-17 13:33 UTC, jzuken commented on sem2/Homework4/task1/src/main/java/group144/uniquelist/stepyrev/List.java
> +    public T removeLast() throws EmptyListException, AlreadyAddedElementException, WrongIndexException {
а остальные исключения не надо документировать?

2019-05-17 13:33 UTC, jzuken commented on sem2/Homework4/task1/src/main/java/group144/uniquelist/stepyrev/List.java
> +package group144.uniquelist.stepyrev;
было бы здорово сделать так, чтобы оно компилировалось без предупреждений

2019-06-06 08:31 UTC, jzuken commented
всё ещё выдаёт ворнинги на List.java

2019-06-10 15:37 UTC, jzuken commented
> Task :compileJava
Note: C:\Users\jetbrains\git\m18\steperev\sem2\Homework4\task1\src\main\java\group144\uniquelist\stepyrev\MyList.java uses unchecked or unsafe operations.

2019-06-10 15:44 UTC, daniil-steperev commented
> > Task :compileJava
> > Note: C:\Users\jetbrains\git\m18\steperev\sem2\Homework4\task1\src\main\java\group144\uniquelist\stepyrev\MyList.java uses unchecked or unsafe operations.

@jzuken Здравствуйте! Извините, подскажите, пожалуйста, где это можно найти. У меня вот так: 
![image](https://user-images.githubusercontent.com/43496856/59207402-abd65980-8baf-11e9-99f6-6c0bfe6155a7.png)
![image](https://user-images.githubusercontent.com/43496856/59207442-bbee3900-8baf-11e9-82de-536d40fed681.png)

2019-06-11 08:15 UTC, merged