added task 2 from hw 4 (avl tree)
daniil-steperev/spbuHomework pull request #95
Opened 2019-03-21 20:18 UTC by daniil-steperev

2019-04-15 12:48 UTC, ujohnny requested changes

2019-04-15 12:48 UTC, ujohnny commented on sem2/Homework4/task2/src/main/java/group144/avltree/stepyrev/AVLTree.java
> +                return true;
стоит как можно меньше использовать несколко return statement внутри ф-и. к примеру эту часть можно было написать как

```
currentNode.quantity--;
if (currentNode.quantity == 0) {
    removeNode();
}
return true;
```

2019-04-15 12:48 UTC, ujohnny commented on sem2/Homework4/task2/src/main/java/group144/avltree/stepyrev/AVLTree.java
> +                if (currentNode.leftChild.currentNode.balanceFactor() > 0) {
как-то оно некрасиво выглядит
`currentNode.leftChild.currentNode.balanceFactor`
зачем вы их разделили в реализации, если у вас вообще циклическая зависимость появляется.

2019-05-03 15:29 UTC, jzuken requested changes

2019-05-03 15:29 UTC, jzuken commented on sem2/Homework4/task2/src/main/java/group144/avltree/stepyrev/AVLTree.java
> +        root = new NodeOperator();
это лучше делать при объявлении поля

2019-05-03 15:29 UTC, jzuken commented on sem2/Homework4/task2/src/main/java/group144/avltree/stepyrev/AVLTree.java
> +            root.addAll(elements);
это какой-то неправильный метод, по этой записи я бы в 100% случаев подумал, что оно добавит в рут все элементы из elements, а тут наоборот совсем

2019-05-03 15:29 UTC, jzuken commented on sem2/Homework4/task2/src/main/java/group144/avltree/stepyrev/AVLTree.java
> +                return true;
согласен. не вижу смысла в подобном разделении

2019-05-03 15:29 UTC, jzuken commented on sem2/Homework4/task2/src/test/java/group144/avltree/stepyrev/AVLTreeTest.java
> +    public void iteratorTest() {
всего один тест на итератор? а там много разных случаев может быть

2019-05-03 15:48 UTC, daniil-steperev commented on sem2/Homework4/task2/src/main/java/group144/avltree/stepyrev/AVLTree.java
> +                return true;
@jzuken Добрый вечер. Я уже исправил эту ошибку в commit 293de828dc372293fdd0aa057983249fe96449f5

2019-05-03 15:55 UTC, jzuken commented on sem2/Homework4/task2/src/main/java/group144/avltree/stepyrev/AVLTree.java
> +                return true;
я не туда комментарий дописал :) это про разделение ноды

2019-05-03 15:59 UTC, daniil-steperev commented on sem2/Homework4/task2/src/main/java/group144/avltree/stepyrev/AVLTree.java
> +                return true;
Понял, спасибо!

2019-05-03 16:09 UTC, daniil-steperev commented
Я решил разделить Node, на NodeOperator, так как мне нужна была ссылка на текущий Node. Это полезно для методов поворота, удаления, так как необходимо просто перекинуть ссылку с одного Node на другой, а не менять вручную все значения.

2019-05-11 14:07 UTC, jzuken requested changes

2019-05-11 14:07 UTC, jzuken commented on sem2/Homework4/task2/src/main/java/group144/avltree/stepyrev/AVLTree.java
> +        private void getAllToList(ArrayList<T> elements) {
не, сильно лучше не стало. почему не сделать метод, который возвращает этот самый список? это куда более объектно-ориентированно

2019-05-11 14:07 UTC, jzuken commented on sem2/Homework4/task2/src/main/java/group144/avltree/stepyrev/AVLTree.java
> +            if (currentNode.leftChild.currentNode == null && currentNode.rightChild.currentNode == null) {
не, я всё ещё против такого разделения, этот код просто нечитаем. в прошлом семестре вы нормально писали деревья без всяких разделений, не вижу ни одной причины делать сейчас иначе

2019-06-06 08:34 UTC, jzuken requested changes

2019-06-06 08:34 UTC, jzuken commented on sem2/Homework4/task2/src/main/java/group144/avltree/stepyrev/Node.java
> +        if (this == null) {
это проверка всегда даст ложь

2019-06-06 08:34 UTC, jzuken commented on sem2/Homework4/task2/src/main/java/group144/avltree/stepyrev/Node.java
> +            if (isRoot(this.value, tree.getRoot())) {
это как-то сильно похоже на копипасту

2019-06-10 15:38 UTC, merged