added task 2 from hw 5 (simple calculator)
daniil-steperev/spbuHomework pull request #98
Opened 2019-03-30 11:25 UTC by daniil-steperev

2019-04-15 14:06 UTC, ujohnny commented on sem2/Homework5/task2/src/main/java/group144/stepyrev/Controller.java
> +        operations.valueProperty().addListener(((observable, oldValue, newValue) -> calculate()));
может быть стоит лямбду один раз инстанциировать?

2019-05-04 17:03 UTC, jzuken requested changes

2019-05-04 17:03 UTC, jzuken commented on sem2/Homework5/task2/src/main/java/group144/stepyrev/Controller.java
> +        operations.valueProperty().addListener(((observable, oldValue, newValue) -> calculate()));
однозначно стоит завести для этого переменную и не писать каждый раз одно и то же

2019-05-04 17:03 UTC, jzuken commented on sem2/Homework5/task2/src/main/java/group144/stepyrev/Controller.java
> +    private void calculate() {
ну вот в такой реализации часть с логикой приложения (подсчёт выражения) неотделима от части обработки UI. её же отдельно не протестировать даже никак. надо разделить их на две сущности

2019-05-11 14:49 UTC, jzuken requested changes

2019-05-11 14:49 UTC, jzuken commented on sem2/Homework5/task2/src/main/java/group144/stepyrev/Controller.java
> +                result = first / second;
ну вообще тут целочисленное деление будет

2019-05-11 14:49 UTC, jzuken commented on sem2/Homework5/task2/src/main/resources/group144/stepyrev/GUI.fxml
> +<GridPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="400.0" prefWidth="600.0" xmlns="http://javafx.com/javafx/8.0.172-ea" xmlns:fx="http://javaf
и окошко всё ещё не зумится

2019-06-06 08:37 UTC, jzuken commented
![2019-06-06 10_36_45-Greenshot](https://user-images.githubusercontent.com/705678/59018803-05085b00-8847-11e9-8c2d-481b4a38eb7f.png)
а можно хоть немного подумать, прежде, чем сдавать?

2019-06-10 15:40 UTC, merged