added task 3 from hw 5 (calculator with buttons)
daniil-steperev/spbuHomework pull request #99
Opened 2019-03-31 17:20 UTC by daniil-steperev

2019-04-15 14:09 UTC, ujohnny commented on sem2/Homework5/task3/build.gradle
> +
тут как то все отформатировано странно и 13 какая то

2019-05-04 17:16 UTC, jzuken requested changes

2019-05-04 17:16 UTC, jzuken commented on sem2/Homework5/task3/src/main/java/group144/stepyrev/Controller.java
> +    public void pressDivideButton() {
все эти методы pressXXXButton различаются только знаками операций

2019-05-04 17:16 UTC, jzuken commented on sem2/Homework5/task3/src/main/resources/group144/stepyrev/GUI.fxml
> +<GridPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="400.0" prefWidth="600.0" xmlns="http://javafx.com/javafx/8.0.172-ea" xmlns:fx="http://javaf
хорошо бы, чтобы окно ещё ресайзилось вместе со всем своим содержимым

2019-06-06 08:39 UTC, jzuken commented
после того, как нажал =, уже никакие операции не применяются

2019-06-10 15:42 UTC, jzuken commented
так оно всё ещё блокирует операции после знака равно. я хочу ввести 1+2=, а потом +5, например

2019-06-11 08:49 UTC, merged